In [5]:
#flatten array
import numpy as np
arr=np.array([[1,2],[3,4]])
flarr=arr.flatten()
print("\n Original array:\n",arr)
print("\n Flatten array:\n",flarr)


 Original array:
 [[1 2]
 [3 4]]

 Flatten array:
 [1 2 3 4]


In [8]:
import numpy as np
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
print("\n No of dimentions:\n",arr.ndim)
print("\n Shape of array:\n",arr.shape)
print("\n Size of array:\n",arr.size)
print("\n Array Type:\n",arr.dtype)
newtype=arr.astype('f')
print("\n converted array element:\n",newtype)
print("\n converted array type:\n",newtype.dtype)


 No of dimentions:
 2

 Shape of array:
 (3, 4)

 Size of array:
 12

 Array Type:
 int32

 converted array element:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]

 converted array type:
 float32


In [9]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])
print(p[2:0:2])
print(p[2:,2:])
print(p[3:,3:])

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]
[]
[[ 9]
 [12]
 [15]]
[]
