In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,4,6,4])
print(arr)
x=np.where(arr==4)
print(x)

[1 2 3 4 5 4 6 4]
(array([3, 5, 7]),)


In [3]:
#indexes where the values are even
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(arr)
print(x)

[1 2 3 4 5 6 7 8]
(array([1, 3, 5, 7]),)


In [4]:
#sorting the array
arr=np.array([3,2,0,1])
print("\nOriginal array",arr)
print("\nSorted array",np.sort(arr))
arr=np.array([[3,2,4],[5,0,1]])
print("\nOriginal array",arr)
print("\nSorted array",np.sort(arr))


Original array [3 2 0 1]

Sorted array [0 1 2 3]

Original array [[3 2 4]
 [5 0 1]]

Sorted array [[2 3 4]
 [0 1 5]]
